apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - dapr-components/inbound-storage.yaml
  - dapr-components/outbound-storage.yaml
  - dapr-components/idempotency-service.yaml
  - dapr-components/business-incident-service.yaml
